// The cross-language wire contract, from the Node side.
//
// golden/wire.jsonl is generated by the Rust side (tests/wire_contract.rs)
// and reviewed like any contract change. This suite pins the CLIENT to the
// same file: every message we can send must byte-match the pinned shape, and
// every pinned server message must decode. If either language drifts, its
// own suite reddens — the drift can no longer hide between two green suites.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { decode, encode, renderLine } from '../src/protocol.js';

const goldenPath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'golden', 'wire.jsonl');
const golden = Object.fromEntries(
  fs
    .readFileSync(goldenPath, 'utf8')
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => {
      const { label, message } = JSON.parse(l);
      return [label, message];
    }),
);

test('every client message we send matches the pinned wire shape', () => {
  const built = {
    history: encode.history('main', { stream: 'main', generation: 1, through: 200, before: 73 }),
    'attach-permissions': encode.attach('main', { capabilities: ['authorize', 'history-pages', 'operation-permissions-v1'] }),
    'set-permission': encode.setPermission('main', 'binding-1', true),
    'authorize-once': encode.authorizeOperation('main', 'binding-1', 'ev_9_feed0004', true, 'once'),
    'authorize-flow': encode.authorizeOperation('main', 'binding-1', 'ev_9_feed0004', true, 'flow'),
    'revoke-grant': encode.revokeGrant('main', 'binding-1', 'grant-1'),
    'attach-basic': encode.attach('main'),
    'attach-derived': encode.attach('btw-1', { template: 'chat', deriveFrom: 'main' }),
    'attach-with-capabilities': encode.attach('main', { capabilities: ['authorize'] }),
    'send-text': encode.sendText('main', 'add 4 and 7'),
    authorize: encode.authorize('main', 'ev_9_feed0004', true),
    detach: encode.detach('main'),
    interrupt: encode.interrupt('main'),
  };
  for (const [label, message] of Object.entries(built)) {
    assert.deepEqual(message, golden[label], `wire drift on ${label}`);
  }
});

test('every pinned server message decodes to the tag the app routes on', () => {
  const wantTag = {
    'attached-paged': 'attached',
    'attached-permissions': 'attached_v2',
    'attached-permissions-unavailable': 'attached_v2',
    'history-page': 'history_page',
    'history-error': 'history_error',
    'attached-with-replay': 'attached',
    'attached-with-warnings': 'attached',
    appended: 'appended',
    notice: 'notice',
    quiescent: 'quiescent',
    'error-with-stream': 'error',
    'error-connection-level': 'error',
  };
  for (const [label, tag] of Object.entries(wantTag)) {
    assert.ok(golden[label], `golden file has no entry for ${label}`);
    const { tag: got, body } = decode(golden[label]);
    assert.equal(got, tag, `decode drift on ${label}`);
    assert.ok(body && typeof body === 'object');
  }
  // The stream field the app routes errors by must survive the trip
  assert.equal(decode(golden['error-with-stream']).body.stream, 'main');
  assert.equal(decode(golden['error-connection-level']).body.stream, null);
});

test('the pinned full envelope renders by the re-emission rule', () => {
  // The pinned envelope is a CAUSED user message — a station's re-emission,
  // which renders nothing (only the causeless typed original shows)
  const { body } = decode(golden.appended);
  assert.equal(renderLine(body.event), null);
  // The same envelope without causes is the typed original — it shows
  assert.deepEqual(renderLine({ ...body.event, causes: [] }), {
    who: 'you',
    text: 'hello wire',
  });
});

test('the golden file covers every message the client can produce', () => {
  // A new encode.* helper without a pinned golden entry means the contract
  // grew silently — this catches the omission on the Node side
  const clientTags = Object.keys(encode).map((name) => name.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`));
  const pinnedTags = new Set(Object.values(golden).map((message) => Object.keys(message)[0]));
  for (const tag of clientTags) {
    assert.ok(pinnedTags.has(tag), `missing golden coverage for encoder ${tag}`);
  }
});
